import profileIcon from "../../assets/Profile-Icon.png";

export const users = [
  {
    id: 1,
    username: "JohnDoe123",
    position: "Remote",
    rating: 4,
    yearsOfExperience: 5,
    location: "New York",
    specialty: "Web Designer",
    productType: "Digital",
    profilePic: profileIcon,
  },
  {
    id: 2,
    username: "SarahSmith",
    position: "Onsite",
    rating: 4.5,
    yearsOfExperience: 8,
    location: "Los Angeles",
    specialty: "Painter",
    productType: "Hand-on",
    profilePic: profileIcon,
  },
  {
    id: 3,
    username: "AlexJohnson",
    position: "Remote",
    rating: 4.9,
    yearsOfExperience: 10,
    location: "Chicago",
    specialty: "Animator",
    productType: "Digital",
    profilePic: profileIcon,
  },
  {
    id: 4,
    username: "EmmaDavis",
    position: "Onsite",
    rating: 4.7,
    yearsOfExperience: 6,
    location: "San Francisco",
    specialty: "Branding",
    productType: "Hand-on",
    profilePic: profileIcon,
  },
  {
    id: 5,
    username: "MarkWilson",
    position: "Remote",
    rating: 4.6,
    yearsOfExperience: 7,
    location: "Miami",
    specialty: "Illustrator",
    productType: "Digital",
    profilePic: profileIcon,
  },
  {
    id: 6,
    username: "LindaWhite",
    position: "Onsite",
    rating: 5,
    yearsOfExperience: 9,
    location: "Boston",
    specialty: "Printer",
    productType: "Hand-on",
    profilePic: profileIcon,
  },
];
